[project]
name = "ai-service"
version = "0.1.0"
description = ""
authors = [
    {name = "Raghav",email = "sairaghavuk@gmail.com"}
]
requires-python = ">=3.12"
dependencies = [
    "fastapi (>=0.133.1,<0.134.0)",
    "uvicorn (>=0.41.0,<0.42.0)",
    "openai (>=2.44.0,<3.0.0)",
    "python-dotenv (>=1.2.2,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
